### ISSUE TITLE
Reason for disabling flattening

### ISSUE THREAD

**Issue by rsglobal** [lineage-rpi/android_external_drm_hwcomposer#1]
Hi,

I saw that you've disabled both writeback and GPU flattening.
Flattening should reduce power consumption.
Could you share your experience?

**Comment by KonstaT** [comment]
Writeback connector is disabled because I'm quite sure it wasn't working on Pi 3 when it was still using 4.14 kernel. I'm not sure if this has changed with newer kernel versions. Even with Pi 4 and 5.4 kernel I see this spammed in logs when writeback is enabled.
```
08-16 10:31:26.950   227   285 E hwc-drm-display-compositor: Could not find drmdevice for display
08-16 10:31:26.950   227   285 E hwc-drm-display-compositor: Failed to init  drmdisplaycompositor = -22
```

GPU flattening is disabled because on Pi 3 it causes the UI to become slow and unresponsive on occasions. It takes ~10 seconds for the UI to return to normal after the glitch. There's also some errors in the logs but couldn't find a logcat with it at the moment.
